### ISSUE TITLE
Loop to same node not working

### ISSUE THREAD

**Issue by MichelBartels** [deepset-ai/canals#67]
When trying to create an agent, I need to store some state in a node. As far as I can tell, the nodes are supposed to be stateless so one alternative is to loop the state back as an input into itself. However, this doesn't work with the current version of canals.

To demonstrate this, I have create the following (slightly non-sensical) example:
```py
from canals import component, Pipeline

@component
class A:
    @component.output_types(goal=int, current=int, final_result=int)
    def run(self, initial_goal: int, goal: int, current: int):
        if initial_goal:
            goal = initial_goal - 1 # For some reason that's a better goal
        if goal == current:
            return {"goal": None, "current": None, "final_result": current}
        return {"goal": goal, "current": current, "final_result": None}

@component
class B:
    @component.output_types(y=int)
    def run(self, x: int):
        return {"y": x + 1}

p = Pipeline()
p.add_component("a", A())
p.add_component("b", B())
p.connect("a.current", "b.x")
p.connect("b.y", "a.current")
p.connect("a.goal", "a.goal")

print(p.run({"a": {"initial_goal": 5, "current": 0}}))
```
B describes a node that is repeatedly called to perform some action (in this case increase a value by 1). A checks this value and sends it back to B until it satisfies a condition (in this case it should be 4). A should be representative of an agent and the current field is its state (in a proper agent this would also change over time. It crashes with the following error:

```
Traceback (most recent call last):
  File "<...>/bug.py", line 26, in <module>
    print(p.run({"a": {"initial_goal": 5, "current": 0}}))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<...>/canals/canals/pipeline/pipeline.py", line 365, in run
    raise PipelineRuntimeError(
canals.errors.PipelineRuntimeError: 'a' is stuck waiting for input, but there are no other components to run. This is likely a Canals bug. Open an issue at https://github.com/deepset-ai/canals.
```

**Comment by ZanSara** [comment]
For additional context, this is the diagram: 

![bug](https://github.com/deepset-ai/canals/assets/5703634/cd997f83-656a-4431-b105-c5acf5ca50bb)

**Comment by MichelBartels** [comment]
Ok, it turns out it wasn't really about looping at all. The error disappears when I fix the input type hints:
```py
from canals import component, Pipeline
from typing import Optional

@component
class A:
    @component.output_types(goal=int, current=int, final_result=int)
    def run(self, initial_goal: Optional[int] = None, goal: Optional[int] = None, current: Optional[int] = None):
        if initial_goal:
            goal = initial_goal - 1 # For some reason that's a better goal
        if goal == current:
            return {"goal": None, "current": None, "final_result": current}
        return {"goal": goal, "current": current, "final_result": None}

@component
class B:
    @component.output_types(y=int)
    def run(self, x: int):
        return {"y": x + 1}

p = Pipeline()
p.add_component("a", A())
p.add_component("b", B())
p.connect("a.current", "b.x")
p.connect("b.y", "a.current")
p.connect("a.goal", "a.goal")

print(p.run({"a": {"initial_goal": 5, "current": 0}}))
```
However, it is still not working because the result is empty.

**Comment by ZanSara** [comment]
@MichelBartels that's correct because your pipeline has no clear output. When does it stop, and how? If you add an output to A() that the component can use to signal that it's stopping, it should work as expected.

**Comment by MichelBartels** [comment]
I would have expected it to stop when A does not output anything that can be fed back to B(). I would have also thought that `final_result` is automatically considered an output because it is not attached to any other node. Do you need to add outputs explicitly? I didn't notice it in the tests.
Something weird also seems to happen because A.run is only called once and B.run isn't called at all.

**Comment by MichelBartels** [comment]
Part of this is definitely a bug. 0 values are considered the same as None. I had this issue earlier already because I can do the following:
```py
print(p.run({"a": {"initial_goal": 5, "current": 0}}))
```
But I can't do this:
```py
print(p.run({"a": {"initial_goal": 5, "current": 1}}))
```
I don't know too much about the codebase so I haven't debugged it properly yet, but I think there is probably some `if value` somewhere which implicitly casts a value into a bool and which treats None and 0 the same way.
This bug also occurs later when A returns `current: 0`, but the pipeline thinks there is no input to B because `bool(0) == false`. There are some workarounds for this which cause A.run and B.run to get called the appropriate number of times, but there is still no output.

**Comment by ZanSara** [comment]
Ok that's really odd, looks like a bug. I'd also say that `final_result` must show as an output. Let's open two issues to track this output detection problem separately and focus on the loop part for this one.

**Comment by MichelBartels** [comment]
I have created opened a PR that should fix the handling of falsy values (#74). Should I close this issue and create another one for output detection because it seems to me that self-loops are actually working?

**Comment by ZanSara** [comment]
I'd say leave this one open to track the linked PR and let's open a new one to check on the output detection :+1:

**Comment by masci** [comment]
This should be fixed with #148 feel free to reopen if that's not the case
